esphome:
  name: alic-smart-plug
  friendly_name: alic_smart_plug

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret alic_smart_plug_params
      ap_ssid: Alic-Smart-Plug
  device: !include
    file: includes/devices/alic_smart_plug/default.yaml

substitutions:
  pw_calibration_current_mult: "0.424471"
  pw_calibration_voltage_div: "816"
  pw_calibration_current_resistor: 0.00112334 ohm

time:
- platform: homeassistant
  id: time_ha
  # This platform does not set the timezone appropriately
  # TODO: should be GMT-3 or America/Argentina/Buenos_Aires
  # esphome messed up the timezone handling
  timezone: "GMT+3"
  on_time:
  - then:
      script.execute:
        id: maybe_restart
        reset_flag: true
    seconds: 30
    minutes: 59
    hours: 23
    # we can do with showing time in 12 hour format to avoid
    # waiting more than 12 hours, just reset it back to 24
    # hour format at 00
  - then:
      script.execute:
        id: maybe_restart
        reset_flag: false
    seconds: 30
    minutes: 59
    hours: 11

script:
- id: blink
  parameters:
    times: uint
  mode: parallel
  then:
    repeat:
      count: !lambda return times*2;
      then:
      - light.toggle: $id_status_light
      - delay: 250ms

- id: maybe_restart
  parameters:
    reset_flag: bool
  then:
    if:
      condition:
      - switch.is_on: restart_at_midnight
      - switch.is_on: $id_relay
      then:
      - switch.turn_off: $id_relay
      - delay: 30s
      - switch.turn_on: $id_relay
      - if:
          condition:
            lambda: return reset_flag;
          then:
            switch.turn_off: restart_at_midnight

binary_sensor:
- id: !extend $id_button
  # clear out the on_press action
  on_press:
    then: []
  on_multi_click:
  - timing:
      - ON for at most 350ms
      - OFF for at most 350ms
      - ON for at most 350ms
      - OFF for at least 50ms
    then:
      switch.toggle: $id_relay
  - timing:
      - ON for at most 350ms
      - OFF for at least 351ms
    then:
      - script.execute:
          id: blink
          times: !lambda |
            return id(restart_at_midnight).state ? 1 : 2;
      - switch.turn_on: restart_at_midnight

switch:
- platform: template
  name: Restart at midnight
  id: restart_at_midnight
  restore_mode: ALWAYS_ON
  optimistic: True
