esphome:
  on_boot:
    # https://esphome.io/components/esphome.html#on-boot after 600 switches are restored
    priority: 600
    then:
      if:
        condition: 
          - switch.is_on: relay
        then:
          - light.turn_on: light_status
  name: alic-smart-plug-3
  friendly_name: alic_smart_plug_3

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret alic_smart_plug_3_params
      ap_ssid: Alic-Smart-Plug-3

bk72xx:
  board: cb2s

sensor:
- platform: hlw8012
  model: BL0937
  cf_pin:
    number: P24
    inverted: true
  cf1_pin:
    number: P26
    inverted: true
  sel_pin:
    number: P10
    inverted: true
  current:
    name: Current
    filters:
    # Calibrated from 1
    - multiply: 0.42996
  voltage:
    name: Voltage
  power:
    name: Power
  energy:
    name: Energy
  # in principle it's 800, but it's been calibrated
  voltage_divider: 775
  # Calibrated from 1mOhm (real value)
  current_resistor: 0.001138 ohm
  update_interval: 5s
  change_mode_every: 1

binary_sensor:
- platform: gpio
  name: Button
  pin:
    number: P6
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: relay

switch:
- platform: gpio
  id: relay
  name: Relay
  pin: P8
  restore_mode: RESTORE_DEFAULT_OFF
  on_turn_on:
    - light.turn_on: light_status
  on_turn_off:
    - light.turn_off: light_status

light:
- platform: status_led
  id: light_status
  pin:
    number: P7
    inverted: true
