esphome:
  on_boot:
    # https://esphome.io/components/esphome.html#on-boot after 600 switches are restored
  - priority: 600
    then:
      if:
        condition:
          switch.is_on: relay_inner
        then:
        - switch.turn_on: relay
        - light.turn_on: light_status
  name: alic-smart-plug-2
  friendly_name: alic_smart_plug_2

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret alic_smart_plug_2_params
      ap_ssid: Alic-Smart-Plug-2

bk72xx:
  board: cb2s

sensor:
- platform: hlw8012
  model: BL0937
  cf_pin:
    number: P24
    inverted: true
  cf1_pin:
    number: P26
    inverted: true
  sel_pin:
    number: P10
    inverted: true
  current:
    name: Current
    filters:
    # Calibrated from 1
      multiply: 0.43612
  voltage:
    name: Voltage
  power:
    name: Power
  energy:
    name: Energy
  # in principle it's 800, but it should calibrate for about 232/237
  voltage_divider: 781
  # Calibrated from 1mOhm
  current_resistor: 0.001163 ohm
  update_interval: 5s
  change_mode_every: 1

binary_sensor:
- platform: gpio
  name: Button
  pin:
    number: P6
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: relay

- platform: template
  id: energy_saving_overwritten
  name: Energy saving overwritten

light:
- platform: status_led
  id: light_status
  pin:
    number: P7
    inverted: true

switch:
- platform: gpio
  id: relay_inner
  internal: True
  pin: P8
  restore_mode: RESTORE_DEFAULT_OFF
  on_turn_on:
  - light.turn_on: light_status
  - script.execute: energy_saving_overwrite
  - script.wait: energy_saving_overwrite
  on_turn_off:
  - light.turn_off: light_status
  - script.execute: energy_saving_overwrite
  - script.wait: energy_saving_overwrite

- platform: template
  id: relay
  name: Relay
  turn_on_action:
  - lambda: |-
      if (!id(load_shed).state || (id(setting_up_load_shedding) && id(turn_on_after_shedding).state)) {
        id(relay_inner).turn_on();
        id(turn_on_after_shedding).turn_on();
        id(relay).publish_state(true);
      } else {
        id(relay_inner).turn_off();
        id(relay).publish_state(false);
      }
  turn_off_action:
  - lambda: |-
      id(relay_inner).turn_off();
      if (!id(setting_up_load_shedding)) {
        id(turn_on_after_shedding).turn_off();
      }
      id(relay).publish_state(false);

- platform: template
  id: load_shed
  name: Load shed
  optimistic: True
  turn_on_action:
  - lambda: |-
      id(setting_up_load_shedding) = true;
      id(relay).turn_off();
      id(setting_up_load_shedding) = false;
  turn_off_action:
  - lambda: |-
      id(setting_up_load_shedding) = true;
      id(relay).turn_on();
      id(setting_up_load_shedding) = false;

- platform: template
  id: turn_on_after_shedding
  name: Turn back on after shedding
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF

- platform: template
  id: energy_saving
  name: Energy saving
  optimistic: True
  turn_off_action:
    then:
    - lambda: |-
        if (!id(energy_saving_overwritten).state) {
          id(setting_up_energy_saving) = true;
          id(relay).turn_on();
        }
        id(energy_saving_overwritten).publish_state(false);

  turn_on_action:
    then:
    - lambda: |-
        if (id(relay).state == false /* if relay is off */) {
          id(energy_saving_overwritten).publish_state(true);
        } else {
          id(setting_up_energy_saving) = true;
          id(relay).turn_off();
        }

globals:
- id: setting_up_energy_saving
  type: bool
  restore_value: no
  initial_value: "false"
- id: setting_up_load_shedding
  type: bool
  restore_value: no
  initial_value: "false"

script:
- id: energy_saving_overwrite
  then:
    - lambda: |-
        id(energy_saving_overwritten).publish_state(
          id(energy_saving).state && !id(setting_up_energy_saving));
        id(setting_up_energy_saving) = false;
