esphome:
  on_boot:
    # https://esphome.io/components/esphome.html#on-boot after 600 switches are restored
    priority: 600
    then:
      if:
        condition: 
          switch.is_on: relay
        then:
          light.turn_on: light_status
  name: alic-smart-plug
  friendly_name: alic_smart_plug

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret alic_smart_plug_params
      ap_ssid: Alic-Smart-Plug

bk72xx:
  board: cb2s

time:
- platform: homeassistant
  id: time_ha
  # This platform does not set the timezone appropriately
  # TODO: should be GMT-3 or America/Argentina/Buenos_Aires
  # esphome messed up the timezone handling
  timezone: "GMT+3"
  on_time:
  - then:
    - if:
        condition:
        - switch.is_on: restart_at_midnight
        - switch.is_on: relay
        then:
        - switch.turn_off: relay
        - delay: 30s
        - switch.turn_on: relay
        - switch.turn_off: restart_at_midnight
    seconds: 30
    minutes: 59
    hours: 23

sensor:
- platform: hlw8012
  model: BL0937
  cf_pin:
    number: P24
    inverted: true
  cf1_pin:
    number: P26
    inverted: true
  sel_pin:
    number: P10
    inverted: true
  current:
    name: Current
    filters:
    # Calibrated from 1
    - multiply: 0.424471
  voltage:
    name: Voltage
  power:
    name: Power
  energy:
    name: Energy
  # in principle it's 800, but it should calibrate for about 243/238
  voltage_divider: 816
  # Calibrated from 1mOhm
  current_resistor: 0.00112334 ohm
  update_interval: 5s
  change_mode_every: 1

binary_sensor:
- platform: gpio
  name: Button
  pin:
    number: P6
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: relay

switch:
- platform: gpio
  id: relay
  name: Relay
  pin: P8
  restore_mode: RESTORE_DEFAULT_OFF
  on_turn_on:
  - light.turn_on: light_status
  on_turn_off:
  - light.turn_off: light_status

- platform: template
  name: Restart at midnight
  id: restart_at_midnight
  restore_mode: ALWAYS_ON
  optimistic: True

light:
- platform: status_led
  id: light_status
  pin:
    number: P7
    inverted: true