esphome:
  name: alic-smart-plug
  friendly_name: alic_smart_plug

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret alic_smart_plug_params
      ap_ssid: Alic-Smart-Plug
  device: !include
    file: includes/devices/alic_smart_plug/default.yaml

substitutions:
  pw_calibration_current_mult: "0.424471"
  pw_calibration_voltage_div: "816"
  pw_calibration_current_resistor: 0.00112334 ohm

time:
- platform: homeassistant
  id: time_ha
  # This platform does not set the timezone appropriately
  # TODO: should be GMT-3 or America/Argentina/Buenos_Aires
  # esphome messed up the timezone handling
  timezone: "GMT+3"
  on_time:
  - then:
      if:
        condition:
        - switch.is_on: restart_at_midnight
        - switch.is_on: $id_relay
        then:
        - switch.turn_off: $id_relay
        - delay: 30s
        - switch.turn_on: $id_relay
        - switch.turn_off: restart_at_midnight
    seconds: 30
    minutes: 59
    hours: 23

switch:
- platform: template
  name: Restart at midnight
  id: restart_at_midnight
  restore_mode: ALWAYS_ON
  optimistic: True
