esphome:
  name: alic-smart-plug-2
  friendly_name: alic_smart_plug_2

substitutions:
  id_relay_inner: relay_inner
  id_em: em_1
  relay_internal: "True"
  pw_calibration_current_mult: "0.43612"
  pw_calibration_voltage_div: "781"
  pw_calibration_current_resistor: 0.001163 ohm

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret alic_smart_plug_2_params
      ap_ssid: Alic-Smart-Plug-2
  em_relay: !include
    file: includes/logic/energy_management/relay.yaml
  device: !include
    file: includes/devices/alic_smart_plug/default.yaml
