esphome:
  name: alic-smart-plug-3
  friendly_name: alic_smart_plug_3

substitutions:
  pw_calibration_current_mult: "0.42996"
  pw_calibration_voltage_div: "775"
  pw_calibration_current_resistor: 0.001138 ohm

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret alic_smart_plug_3_params
      ap_ssid: Alic-Smart-Plug-3
  device: !include
    file: includes/devices/alic_smart_plug/default.yaml
