esphome:
  on_boot:
    # https://esphome.io/components/esphome.html#on-boot after 600 switches are restored
  - priority: 600
    then:
      if:
        condition:
          switch.is_on: $id_relay_inner
        then:
          light.turn_on: light_status
  name: alic-smart-plug-3
  friendly_name: alic_smart_plug_3

substitutions:
  id_relay_inner: relay_inner
  id_relay: relay

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret alic_smart_plug_3_params
      ap_ssid: Alic-Smart-Plug-3
  energy_management: !include
    file: includes/logic/energy_saving_and_load_shedding.yaml
    vars:
      id_energy_saving_overwritten: energy_saving_overwritten
      id_load_shed: load_shed
      id_turn_on_after_shedding: turn_on_after_load_shedding
      id_energy_saving: energy_saving

bk72xx:
  board: cb2s

sensor:
- platform: hlw8012
  model: BL0937
  cf_pin:
    number: P24
    inverted: true
  cf1_pin:
    number: P26
    inverted: true
  sel_pin:
    number: P10
    inverted: true
  current:
    name: Current
    filters:
    # Calibrated from 1
      multiply: 0.42996
  voltage:
    name: Voltage
  power:
    name: Power
  energy:
    name: Energy
  # in principle it's 800, but it's been calibrated
  voltage_divider: 775
  # Calibrated from 1mOhm (real value)
  current_resistor: 0.001138 ohm
  update_interval: 5s
  change_mode_every: 1

binary_sensor:
- platform: gpio
  name: Button
  pin:
    number: P6
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    switch.toggle: $id_relay

light:
- platform: status_led
  id: light_status
  pin:
    number: P7
    inverted: true

switch:
- platform: gpio
  id: $id_relay_inner
  internal: True
  pin: P8
  restore_mode: RESTORE_DEFAULT_OFF
  on_turn_on:
    light.turn_on: light_status
  on_turn_off:
    light.turn_off: light_status
