esphome:
  name: baw-smart-relay-pw-2
  friendly_name: baw_smart_relay_pw_2

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret baw_smart_relay_pw_2_params
      ap_ssid: Baw-Smart-Relay-Pw-2
  device: !include
    file: includes/devices/desmaled_smart_relay_pw/default.yaml
    vars:
      # Voltage and current calibration ended up within
      # noise margins
      power_calibration: "-1"

bk72xx:
  board: cb2s
