esphome:
  name: desmaled-smart-relay-pw-1
  friendly_name: desmaled_smart_relay_pw_1

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret desmaled_smart_relay_pw_1_params
      ap_ssid: Desmaled-Smart-Relay-Pw-1
  device: !include
    file: includes/devices/desmaled_smart_relay_pw/default.yaml