esphome:
  name: din-mounted-relay
  friendly_name: din_mounted_relay

substitutions:
  id_relay_inner: relay_inner
  id_relay: relay

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret din_mounted_relay_params
      ap_ssid: Din-Mounted-Relay
  more_debug_lt: !include includes/more_debug_libretiny.yaml
  energy_management: !include
    file: includes/logic/energy_saving_and_load_shedding.yaml
    vars:
      id_energy_saving_overwritten: energy_saving_overwritten
      id_load_shed: load_shed
      id_turn_on_after_shedding: turn_on_after_load_shedding
      id_energy_saving: energy_saving

bk72xx:
  board: generic-bk7231t-qfn32-tuya

captive_portal:

web_server:

status_led:
  pin:
    number: P1
    inverted: true

binary_sensor:
- platform: gpio
  name: Button
  pin:
    number: P26
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    switch.toggle: $id_relay

switch:
- platform: gpio
  id: $id_relay_inner
  internal: True
  pin: P14
  restore_mode: RESTORE_DEFAULT_OFF
