esphome:
  on_boot:
    # https://esphome.io/components/esphome.html#on-boot after 600 switches are restored
    priority: 600
    then:
    - if:
        condition: 
          - switch.is_on: switch_1
        then:
          - switch.turn_on: switch_1_inner
    - if:
        condition: 
          - switch.is_on: switch_2
        then:
          - switch.turn_on: switch_2_inner
  name: macroled-mini-relay-1
  friendly_name: macroled_mini_relay_1

packages:
  basic: !include
    file: includes/basic.yaml
    vars:
      # secrets don't support substitution
      # CHANGE THIS TO THE NAME OF THE DEVICE!!!
      <<: !secret macroled_mini_relay_1_params
      ap_ssid: Macroled-Mini-Relay-1

bk72xx:
  board: generic-bk7231n-qfn32-tuya

binary_sensor:
- platform: gpio
  id: binary_onoff_1
  name: Switch 1
  pin:
    number: P24
    inverted: true
    mode: INPUT_PULLUP
  on_press: 
    then:
    - switch.turn_on: switch_1
  on_release: 
    then:
    - switch.turn_off: switch_1
- platform: gpio
  id: binary_onoff_2
  name: Switch 2
  pin:
    number: P26
    inverted: true
    mode: INPUT_PULLUP
  on_press: 
    then:
    - switch.turn_on: switch_2
  on_release: 
    then:
    - switch.turn_off: switch_2
- platform: gpio
  id: binary_switch_all
  pin:
    number: P10
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: switch_1
    - switch.toggle: switch_2

switch:
- platform: template
  id: switch_1
  name: Relay 1
  optimistic: True
  on_turn_on:
  - switch.turn_on: switch_1_inner
  on_turn_off:
  - switch.turn_off: switch_1_inner

- platform: gpio
  id: switch_1_inner
  name: Relay 1
  pin: P8
  restore_mode: RESTORE_DEFAULT_OFF

- platform: template
  id: switch_2
  name: Relay 2
  optimistic: True
  on_turn_on:
  - switch.turn_on: switch_2_inner
  on_turn_off:
  - switch.turn_off: switch_2_inner

- platform: gpio
  id: switch_2_inner
  name: Relay 2
  pin: P7
  restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: P6
    inverted: true
