sensor:
- platform: wifi_signal
  name: WiFi Signal
  update_interval: 60s
  entity_category: diagnostic

- platform: uptime
  name: Uptime
  entity_category: diagnostic

button:
- platform: restart
  name: Restart
  entity_category: diagnostic
